version: "3.9"
services:
  data_ingestion:
    container_name: data_ingestion_container
    build: ./src/data_ingestion
    ports:
      - "8000:8000"
    networks:
      - my_network
  database_api:
    container_name: database_api_container
    build: ./src/database_api
    restart: always
    depends_on:
      - database
    ports:
      - "9000:9000"
    networks:
      - my_network
  database:
    container_name: database_container
    build: ./src/database
    ports:
      - "6603:3306"
    networks:
      - my_network
  frontend:
    container_name: frontend_container
    build: ./src/frontend
    depends_on:
      - database_api
    ports:
      - "3000:80"
    networks:
      - my_network
  backend_service:
    container_name: backend_service_container
    build: ./src/backend_services/prediction
    ports:
      - "8001:8001"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
