version: "3.9"
services:
  data_ingestion:
    container_name: data_ingestion_container
    build: ./data_ingestion
    ports:
      - "8000:8000"
    networks:
      - my_network
  database_api:
    container_name: database_api_container
    build: ./mysql_api
    restart: always
    ports:
      - "9000:9000"
    networks:
      - my_network
  database:
    container_name: database_container
    build: ./mysql
    ports:
      - "6603:3306"
    networks:
      - my_network
  frontend:
    container_name: frontend_container
    build: ./dir
    ports:
      - "5173:5173"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
