CREATE DATABASE ExchangeRate;
USE ExchangeRate;

CREATE TABLE tbDollarToJPY (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rate DECIMAL(9, 6),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tbDollarToGBP (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rate DECIMAL(9, 6),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tbDollarToEUR (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rate DECIMAL(9, 6),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);